cb372/cats-retry

- modules/core/shared/src/main/scala/retry/RetryPolicy.scala
- modules/core/shared/src/test/scala/retry/RetryPolicySpec.scala
- modules/docs/src/main/tut/docs/policies.md
Having an instance of monoid wasn't reflecting all proprieties the
implementation had. This commit change it by an instance of
BoundedSemillatice that reflect the idempotent propriety.
Documentation have been updated accordingly.
> Replace Monoid policy instance by BoundedSemillatice

- .travis.yml
This was a relic from when I was planning to publish the microsite via
Travis. For now I'm happy to publish it manually so I'll get rid of it.
It slows down the build and appears to have broken at some point
recently (see https://travis-ci.org/cb372/cats-retry/builds/472633596)
> Remove unused Jekyll stuff from Travis config

- modules/core/shared/src/main/scala/retry/implicits.scala
- modules/core/shared/src/main/scala/retry/syntax/all.scala
- modules/core/shared/src/main/scala/retry/syntax/package.scala
- modules/core/shared/src/main/scala/retry/syntax/retry.scala
- modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
- modules/docs/src/main/tut/docs/combinators.md
Having syntactic sugar allows to reduce boilerplate. We also push Policy
and onError handler implicitly to this end.
I must admit the design could be improved in the future by creating some
intermediate level of implicit passing. Also using call-by-name doesn't
allow AnyVal extending of the implicit extension class and so reducing
boilerplate
Tests and docs have been added,
> Introduce syntactic sugar

- .travis.yml
- modules/core/shared/src/test/scala/retry/RetryPoliciesSpec.scala
Now we have a mixture of modules with different cross-build configs, using `++$TRAVIS_SCALA_VERSION` doesn't work properly. Replaced it with a single Travis build that calls `sbt +test`.
> Get rid of Travis Scala matrix

- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/test/scala/retry/RetryPoliciesSpec.scala
- modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala
Add checks to all the backoff-based retry policies to avoid creating a FiniteDuration longer than Long.MaxValue nanoseconds, because that results in an exception.
Also:
* add a test to reproduce the issue
* Override minSuccessful so we run 100 tests, not the ScalaTest default of 10
Fixes #96
> Avoid FiniteDuration overflow

- modules/cats-effect/shared/src/main/scala/retry/CatsEffect.scala
- modules/core/js/src/main/scala/retry/Sleep.scala
- modules/core/jvm/src/main/scala/retry/Sleep.scala
- modules/core/shared/src/main/scala/retry/Fibonacci.scala
- modules/core/shared/src/main/scala/retry/PolicyDecision.scala
- modules/core/shared/src/main/scala/retry/RetryDetails.scala
- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/main/scala/retry/RetryPolicy.scala
- modules/core/shared/src/main/scala/retry/RetryStatus.scala
- modules/core/shared/src/main/scala/retry/package.scala
- modules/core/shared/src/main/scala/retry/syntax/retry.scala
- modules/core/shared/src/test/scala/retry/FibonacciSpec.scala
- modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
- modules/core/shared/src/test/scala/retry/RetryPoliciesSpec.scala
- modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala
- modules/core/shared/src/test/scala/retry/RetryPolicySpec.scala
- modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
- modules/docs/src/main/scala/util/FlakyHttpClient.scala
- modules/docs/src/main/scala/util/LoadedDie.scala
- modules/monix/shared/src/main/scala/retry/Monix.scala
- modules/monix/shared/src/test/scala/retry/MonixSpec.scala
Apparently scalafmt's formatting rules changed between 2.2.1 and 2.2.2. That's kind of annoying.
> Re-apply formatter

- .github/workflows/ci.yml
References:
https://github.com/postmanlabs/postman-docs/blob/eb7f6d8545a32f32cef5d549622d61b6987e6009/.github/workflows/ci.yml
https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979/page/3
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories
> Apparently we are supposed to use the pull_request event?

- modules/core/jvm/src/test/scala/retry/PackageObjectLazinessSpec.scala
- modules/core/shared/src/main/scala/retry/package.scala
After an attempt has failed, we need to do the following *sequentially*:
1. delay for as long as the retry policy tells us to
2. execute another attempt
Unfortunately we were accidentally using `*>` to sequence these actions. This is eager in both arguments. That's not so bad when using cats-effect `IO`, but when using `Future` it means we start executing the next attempt before we execute the delay!
Replaced all occurrences of `*>` with `>>`, which is lazy in its second argument.
Fixes #116
> Fix accidental eager evaluation of action

- .github/workflows/release.yml
- build.sbt
No need to mess around with custom sbt commands just to run the tests before releasing. I got a bit carried away last night.
> Simplify usage of sbt-ci-release

- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/main/scala/retry/RetryPolicy.scala
Renders like this:
```scala
scala> RetryPolicies.capDelay(20.seconds, RetryPolicies.exponentialBackoff(1.second))
res70: retry.RetryPolicy[cats.package.Id] = exponentialBackOff(baseDelay=1 second).meet(constantDelay(20 seconds))
```
Should fix #123
> Add ability to pretty print policies

- modules/core/shared/src/main/scala/retry/package.scala
- modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
- modules/mtl/shared/src/main/scala/retry/mtl/package.scala
- modules/mtl/shared/src/test/scala/retry/mtl/PackageObjectSpec.scala
Fix #206
* Rewrote the combinators in the core and mtl modules to use `tailRecM`
* Added stack safety tests
* Rewrote the `retryingOnAllErrors` combinator to call `retryingOnSomeErrors`, removing a lot of duplicated code. This never occurred to me before but I noticed that @iRevive had done it in the mtl module 👌
> Stack safety

- modules/core/shared/src/main/scala/retry/syntax/retry.scala
- modules/docs/src/main/mdoc/docs/combinators.md
* Add more examples
* Tweak the code samples
* Remove a reference to a deleted example
> Update the combinators doc page

- build.sbt
- modules/alleycats/jvm/src/main/scala/retry/alleycats/instances.scala
- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/main/scala/retry/Sleep.scala
- modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
- modules/core/shared/src/test/scala/retry/RetryPoliciesSpec.scala
- modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
- modules/docs/src/main/mdoc/docs/mtl-combinators.md
- modules/mtl/shared/src/main/scala/retry/mtl/package.scala
- modules/mtl/shared/src/main/scala/retry/mtl/syntax/retry.scala
- modules/mtl/shared/src/test/scala/retry/mtl/PackageObjectSpec.scala
- modules/mtl/shared/src/test/scala/retry/mtl/SyntaxSpec.scala
- project/plugins.sbt
- Drop Scala 2.11 support
- Update scalajs to 1.2.0
- Update cats, cats-effect to 2.2.0
- Update cats-mtl to 1.0.0
> Update libraries (cats, cats-effect, cats-mtl, scalatest), drop Scala 2.11 support

- .github/workflows/ci.yml
- .github/workflows/release.yml
This should fix the deprecation warnings we see on the Actions page, and might fix the weird hanging step in the release workflow.
> Update all GH actions to latest versions

- modules/docs/src/main/mdoc/docs/combinators.md
- modules/docs/src/main/mdoc/docs/mtl-combinators.md
- Fix the type signatures in the docs
- Add a combinators cheat sheet
Fixes #255
> Improve combinators documentation

- build.sbt
- modules/core/shared/src/main/scala/retry/Sleep.scala
- modules/docs/src/main/mdoc/docs/combinators.md
- modules/docs/src/main/mdoc/docs/index.md
- modules/docs/src/main/mdoc/docs/mtl-combinators.md
- modules/docs/src/main/mdoc/docs/policies.md
- modules/docs/src/main/mdoc/docs/sleep.md
- project/plugins.sbt
removed dependency to io.monix which is not yet available for CE3..
> "migrate" to cats effect 3 

- modules/core/shared/src/main/scala/retry/ResultHandler.scala
- modules/core/shared/src/test/scala/retry/CombinatorsSuite.scala
- modules/core/shared/src/test/scala/retry/SyntaxSuite.scala
- modules/docs/src/main/mdoc/docs/combinators.md
- modules/docs/src/main/mdoc/docs/index.md
- modules/docs/src/main/mdoc/docs/migration.md
- modules/docs/src/main/resources/microsite/data/menu.yml
Closes #531 
* Add flowcharts to explain the logic for each combinator
* Write a migration guide to help people migrate from v3
* Add a helper method for building an error handler that retries on some errors
* Use the helper methods where possible in the unit tests
> Add a v3 -> v4 migration guide

- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/main/scala/retry/RetryPolicy.scala
- modules/core/shared/src/main/scala/retry/package.scala
- modules/core/shared/src/main/scala/retry/syntax/RetrySyntax.scala
- modules/core/shared/src/test/scala/retry/RetryPoliciesSuite.scala
- modules/core/shared/src/test/scala/retry/RetryPolicyLawsSuite.scala
- modules/core/shared/src/test/scala/retry/RetryPolicySuite.scala
- modules/docs/src/main/mdoc/docs/migration.md
- modules/docs/src/main/mdoc/docs/mtl-combinators.md
- modules/docs/src/main/mdoc/docs/policies.md
- modules/mtl/shared/src/main/scala/retry/mtl/package.scala
- modules/mtl/shared/src/main/scala/retry/mtl/syntax/RetrySyntax.scala
Fixes #506.
When asking the retry policy to decide the next step, pass the result of the last attempt. Depending on the combinator, this could be a value or an error.
Before:
```scala
case class RetryPolicy[F[_]](
decideNextRetry: RetryStatus => F[PolicyDecision]
)
```
After:
```scala
case class RetryPolicy[F[_], -Res](
decideNextRetry: (Res, RetryStatus) => F[PolicyDecision]
)
```
This allows users to implement more exotic retry policies, e.g. choosing to retry some kinds of error quickly, but using exponential backoff for others. I've added `RetryPolicies.dynamic` to support that.
All the built-in policies maintain their existing behaviour: they ignore the action result and decide the next step based on static rules.
This was quite a noisy change because it involved adding a new type …
> Dynamic retry policies

- build.sbt
- modules/core/shared/src/main/scala/retry/RetryPolicies.scala
- modules/core/shared/src/test/scala/retry/RetryPoliciesSuite.scala
Replace scala.util.Random with CE Random
> Use Cats Effect Random for randomness in fullJitter

- build.sbt
Sets the `versionScheme` property as `semver-spec`, which will prevent issues with `eviction` and the new `4` release.
> Configure the `versionScheme` property for sbt
