cb372/cats-retry

build.sbt
modules/core/src/main/scala/retry/RetryPolicy.scala
modules/core/src/test/scala/retry/PackageObjectSpec.scala
modules/monix/src/main/scala/retry/Monix.scala
modules/monix/src/test/scala/retry/MonixSpec.scala

I found a better way to support Monix and also added a test using `TestScheduler` (https://monix.io/docs/3x/execution/scheduler.html#injecting-time-and-tests).
I enabled a few compiler options that can be handy (i.e. dead code, unused imports, etc). Let me know if that's okay with you.

better monix support

---

build.sbt
modules/docs/src/main/tut/docs/index.md
modules/docs/src/main/tut/docs/sleep.md
project/build.properties

Upgrade cats-effect to 1.0.0

---

modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala

This should improve randomness of retrypolicy by quite a bit :) 
Fixes #40

Use Cogen for arbitrary of RetryPolicy

---

build.sbt
modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala

It's not exactly Exhaustive, but should give some slightly better results than what we had before.
Fixes #41

Improve Eq[RetryStatus]

---

modules/core/shared/src/main/scala/retry/RetryPolicy.scala
modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala

Just some extra combinators I thought might be useful. :)

Add mapDelay, flatMapDelay and mapK combinators

---

.scalafmt.conf
.travis.yml
build.sbt
modules/core/shared/src/main/scala/retry/RetryPolicies.scala
modules/core/shared/src/main/scala/retry/RetryPolicy.scala
modules/core/shared/src/main/scala/retry/syntax/retry.scala
modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
modules/core/shared/src/test/scala/retry/RetryPoliciesSpec.scala
modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala
modules/core/shared/src/test/scala/retry/RetryPolicySpec.scala
modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
project/LatestVersionPlugin.scala
project/plugins.sbt

Upgrade Scalafmt

---

build.sbt
modules/core/shared/src/test/scala/retry/RetryPolicyLawsSpec.scala

* cats 2.0.0
* cats-effect 2.0.0
* Monix 3.0.0
* Scala 2.12.10
* scalatest 3.1.0-RC2

Upgrade party!

---

modules/docs/src/main/tut/docs/combinators.md

Documentation Corrections

---

modules/core/shared/src/main/scala/retry/RetryDetails.scala

Add common fields to RetryDetails

---

modules/core/shared/src/main/scala/retry/syntax/retry.scala
modules/core/shared/src/test/scala/retry/SyntaxSpec.scala

Adapt syntax for better type inference and pass params explicitly

---

modules/docs/src/main/mdoc/docs/combinators.md

It was broken by #131 but wasn't being checked my mdoc

Fix code sample in doc

---

build.sbt

Fixes build from https://github.com/cb372/cats-retry/pull/252

Update cats-core to 2.3.0

---

.github/workflows/ci.yml
.gitignore
modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/main/scala/retry/syntax/retry.scala
modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
modules/docs/src/main/mdoc/docs/combinators.md
modules/docs/src/main/scala/util/FlakyHttpClient.scala

Functionality to Retry Failures and Errors In The Same Retry Strategy

---

.bsp/sbt.json
modules/alleycats/jvm/src/test/scala/retry/alleycats/PackageObjectLazinessSpec.scala
modules/alleycats/shared/src/main/scala/retry/alleycats/syntax.scala
modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/main/scala/retry/syntax/retry.scala
modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
modules/docs/src/main/mdoc/docs/combinators.md

I created this per the comment here: https://github.com/cb372/cats-retry/pull/259#discussion_r543531726
I am happy to resolve conflicts between the base branch and this one depending on what is merged first. Just wanted to open it for discussion.

Rename retryingM to retryingOnFailures

---

modules/alleycats/jvm/src/test/scala/retry/alleycats/PackageObjectLazinessSpec.scala
modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/main/scala/retry/syntax/retry.scala
modules/core/shared/src/test/scala/retry/PackageObjectSpec.scala
modules/core/shared/src/test/scala/retry/SyntaxSpec.scala
modules/docs/src/main/mdoc/docs/combinators.md
modules/docs/src/main/mdoc/docs/mtl-combinators.md
modules/mtl/shared/src/main/scala/retry/mtl/package.scala
modules/mtl/shared/src/main/scala/retry/mtl/syntax/retry.scala
modules/mtl/shared/src/test/scala/retry/mtl/PackageObjectSpec.scala
modules/mtl/shared/src/test/scala/retry/mtl/SyntaxSpec.scala

This is what the retry haskell library does, and allows to retry on effectful operations.

Fix #283: Change bool functions to m bool

---

modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/test/scala/retry/CombinatorsSuite.scala
modules/mtl/shared/src/main/scala/retry/mtl/package.scala
modules/mtl/shared/src/test/scala/retry/mtl/CombinatorsSuite.scala

* Remove package objects and use top-level declarations instead
* Rename corresponding test suites

Remove the remaining package objects

---

modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/main/scala/retry/syntax/RetrySyntax.scala
modules/core/shared/src/test/scala/retry/CombinatorsSuite.scala
modules/docs/src/main/mdoc/docs/adaptation.md
modules/docs/src/main/mdoc/docs/combinators.md
modules/docs/src/main/mdoc/docs/index.md
modules/docs/src/main/mdoc/docs/mtl-combinators.md
modules/mtl/shared/src/main/scala/retry/mtl/package.scala
modules/mtl/shared/src/main/scala/retry/mtl/syntax/RetrySyntax.scala
modules/mtl/shared/src/test/scala/retry/mtl/CombinatorsSuite.scala

Reorder params

---

modules/core/shared/src/main/scala/retry/package.scala
modules/core/shared/src/main/scala/retry/syntax/RetrySyntax.scala
modules/core/shared/src/test/scala/retry/CombinatorsSuite.scala
modules/core/shared/src/test/scala/retry/SyntaxSuite.scala
modules/docs/src/main/mdoc/docs/adaptation.md
modules/docs/src/main/mdoc/docs/combinators.md

Return result wrapped in an Either to indicate success/failure

---

build.sbt

@AlejandroBudy @ccantarero91 Are you both OK with being immortalised in `pom.xml`?

Add new devs to POM

---

.github/workflows/ci.yml
.github/workflows/release.yml

sbt is no longer present on the Ubuntu runners.
https://github.com/actions/setup-java/issues/712#issuecomment-2557396980

Install sbt in GH actions

---

modules/docs/src/main/mdoc/docs/migration.md

I forgot to update them as part of #550

Update method signatures in migration guide
